export enum ERROR_MESSAGES {
  INAVALID_API_KEY_FORMAT = 'INAVALID_API_KEY_FORMAT',
  INAVALID_UID_FORMAT = 'INAVALID_UID_FORMAT',
  INAVALID_URI_FORMAT = 'INAVALID_URI_FORMAT',
  INAVALID_EMAIL_FORMAT = 'INAVALID_EMAIL_FORMAT',
  INAVALID_GSM_FORMAT = 'INAVALID_GSM_FORMAT'
}

